name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # E

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Authenticate with Cloudflare
        run: echo "$CF_API_TOKEN" | wrangler login
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Publish to Cloudflare
        run: wrangler publish
